driver:
  name: docker
provisioner:
  name: chef_solo
platforms:
  - name: centos-7.1
    driver_config:
      privileged: true
      run_command: /usr/sbin/init
      provision_command:
        - yum install -y tar curl python-setuptools 
suites:
  - name: influxcontainer 
    run_list:
    - "recipe[influx::default]"
    attributes:
